services:

  php:
    image: fam-app
    container_name: FAM-php
    expose:
      - "9000"
    networks:
      - appnet
    depends_on:
      - db
    environment:
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: mysql:latest
    container_name: FAM-db
    networks:
      - appnet
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3233:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/schema.sql

  caddy:
    image: fam-caddy
    container_name: FAM-caddy
    networks:
      - appnet
    ports:
      - "80:80"
      - "443:443"
    
    volumes:
      - ./docker/caddy/CaddyfileProd:/etc/caddy/Caddyfile
      - ./docker/ssl:/etc/caddy/certs   # added for localhost domain

networks:
  appnet:

volumes:
  db_data: