name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:   # GLOBAL ENV (available to all steps)
      APP_ENV: ${{ vars.APP_ENV }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_PORT: ${{ vars.DB_PORT }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ vars.DB_NAME }}
      MYSQL_USER: ${{ vars.DB_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: PHP lint
        run: find . -name "*.php" -exec php -l {} \;

      # Build images
      - name: Build PHP image
        run: docker build -t fam-php -f docker/php/Dockerfile .

      - name: Build Caddy image
        run: docker build -t fam-caddy -f docker/caddy/Dockerfile .

      # Start services (env automatically passed)
      - name: Start containers
        run: docker compose -f docker-compose-prod.yml up -d

      # Smoke test
      - name: Smoke test
        run: |
          for i in {1..10}; do
            if curl -f http://fam.localhost; then
              exit 0
            fi
            sleep 2
          done
          docker compose -f docker-compose-prod.yml logs
          exit 1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag images
        run: |
          docker tag fam-php ${{ secrets.DOCKER_USERNAME }}/fam-php:latest
          docker tag fam-caddy ${{ secrets.DOCKER_USERNAME }}/fam-caddy:latest

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fam-php:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/fam-caddy:latest

      # Cleanup
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose-prod.yml down -v